### ISSUE TITLE
Issue with mouse capture service?

### ISSUE THREAD

**Issue by andrewboni** [codecapers/AngularJS-FlowChart#8]
First of all, thanks for your work on this Ashley.

I'm playing around with this, and when I try to drag or connect any of the nodes, I get this error:

``` javascript
Raven: Exception  TypeError: undefined is not a function
    at Object.release (http://localhost:9000/assets/lib/AngularJS-FlowChart/flowchart/mouse_capture_service.js:97:13)
    at Object.acquire (http://localhost:9000/assets/lib/AngularJS-FlowChart/flowchart/mouse_capture_service.js:68:9)
    at Object.startDrag (http://localhost:9000/assets/lib/AngularJS-FlowChart/flowchart/dragging_service.js:92:17)
    at k.FlowChartController.$scope.connectorMouseDown (http://localhost:9000/assets/lib/AngularJS-FlowChart/flowchart/flowchart_directive.js:357:12)
    at http://localhost:9000/assets/lib/angular/angular.min.js:176:141
    at http://localhost:9000/assets/lib/angular/angular.min.js:193:165
    at k.$eval (http://localhost:9000/assets/lib/angular/angular.min.js:112:319)
    at k.$apply (http://localhost:9000/assets/lib/angular/angular.min.js:113:48)
    at SVGGElement.<anonymous> (http://localhost:9000/assets/lib/angular/angular.min.js:193:147)
    at SVGGElement.n.event.dispatch (http://localhost:9000/assets/lib/jquery/dist/jquery.min.js:3:6404) undefined 
```

Any ideas why?

I'm using the following:
- Angular 1.2.19
- jQuery 2.1.1

Thanks!

**Comment by Underskay** [comment]
I got this error: 

```javascript

TypeError: $element.unbind is not a function
    at Object.release (http://0.0.0.0:3000/plugins/flowchart/mouse_capture_service.js:97:13)
    at Object.acquire (http://0.0.0.0:3000/plugins/flowchart/mouse_capture_service.js:68:9)
    at Object.startDrag (http://0.0.0.0:3000/plugins/flowchart/dragging_service.js:92:17)
    at Scope.FlowChartController.$scope.nodeMouseDown (http://0.0.0.0:3000/plugins/flowchart/flowchart_directive.js:294:12)
    at fn (eval at <anonymous> (http://0.0.0.0:3000/plugins/angular/angular.js:13275:15), <anonymous>:4:427)
    at callback (http://0.0.0.0:3000/plugins/angular/angular.js:23481:17)
    at Scope.$eval (http://0.0.0.0:3000/plugins/angular/angular.js:15922:28)
    at Scope.$apply (http://0.0.0.0:3000/plugins/angular/angular.js:16022:25)
    at SVGGElement.<anonymous> (http://0.0.0.0:3000/plugins/angular/angular.js:23486:23)
    at SVGGElement.jQuery.event.dispatch (https://code.jquery.com/jquery-2.1.4.js:4435:9)
```

The error was solved using @andrewboni solution, thanks!
